name: world-scrape
services:
  frontend:
    container_name: ws-frontend-container
    image: ws-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.angular
      args:
        - WS_FE_CONFIG=staging
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    container_name: ws-backend-container
    image: ws-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/worldscrape?serverTimezone=UTC

      WS_SCRAPAPER_URL: http://ws-scrapaper-container:5100
      #WS_FRONTEND_URL: http://ws-frontend-container:4200
      WS_JWT_SECRET_KEY: 3s6v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVjgfjtytfbutfuyvhdsdfghnmljgxschdrvftjk

      #AMZ_ACCESS_KEY: <your access key>
      #AMZ_SECRET_KEY: <your secret key>
      AMZ_REGION: eu-central-1
      AMZ_BUCKET_NAME: world-scrape
      #AMZ_BUCKET_NAME: world-scrape-prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - scrapaper
  scrapaper:
    container_name: ws-scrapaper-container
    image: ws-scrapaper:latest
    build: ./scrapaper
    environment:
      WS_JWT_SECRET_KEY: 3s6v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVjgfjtytfbutfuyvhdsdfghnmljgxschdrvftjk
    ports:
      - "5100:5100"
  mysql:
    container_name: mysql-container
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: download99
      MYSQL_DATABASE: worldscrape
    ports:
      - "3307:3306"
