FROM openjdk:17-alpine
COPY /target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]

#FROM openjdk:17-alpine as build
#COPY mvnw .
#COPY .mvn .mvn
#COPY pom.xml .
#COPY /src/main /src/main
#COPY /src/test /src/test
#
#RUN chmod +x mvnw
#RUN ./mvnw install -DskipTests
#
#FROM openjdk:17-alpine
#COPY --from=build /target/*.jar app.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","/app.jar"]
