name: world-scrape
services:
  frontend:
    container_name: ws-frontend-container
    image: ws-frontend:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.angular
      args:
        - WS_FE_CONFIG=staging
        #- WS_FE_CONFIG=production
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    container_name: ws-backend-container
    image: ws-backend:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/worldscrape?serverTimezone=UTC

      #WS_SCRAPAPER_URL: http://scrapaper:5100
      #WS_FRONTEND_URL: https://world-scrape.com
      WS_JWT_SECRET_KEY: 3s6v9yAB&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVjgfjtytfbutfuyvhdsdfghnmljgxschdrvftjk


      #AMZ_ACCESS_KEY: <your access key>
      #AMZ_SECRET_KEY: <your secret key>
      AMZ_REGION: eu-central-1
      AMZ_BUCKET_NAME: world-scrape
      #AMZ_BUCKET_NAME: world-scrape-prod
    ports:
      - "6969:8080"
    depends_on:
      - mysql
      - scrapaper
  scrapaper:
    container_name: ws-scrapaper-container
    image: ws-scrapaper:latest
    build: ./scrapaper
    restart: always
    environment:
      WS_JWT_SECRET_KEY: "3s6v9yAB&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVjgfjtytfbutfuyvhdsdfghnmljgxschdrvftjk"
      #WS_FRONTEND_URL: https://world-scrape.com
      CHROME_LOCATION: /usr/bin/chromium-browser
      DRIVER_PATH: /usr/bin/chromedriver
    ports:
      - "5100:5100"
  mysql:
    container_name: mysql-container
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: download99
      MYSQL_DATABASE: worldscrape
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql_scripts/worldscrape.sql:/docker-entrypoint-initdb.d/1.sql
